### PR TITLE
SnoopCompile

### PR DESCRIPTION
**Pull request by aminya**
Ready to get merged

Atom infer time is enhanced by 19% 🚀

### CODE REVIEW

**Comment by pfitzseb** [comment]
Can you check by how much does this improve package load times/time to first eval?

I was under the impression that precompile statements that reach into dependencies don't really work (i.e. aren't cached in ji files), so it's possible that most of the files added here won't make much of a difference.

**Comment by aminya** [comment]
Yes, only "deps/SnoopCompile/precompile/precompile_Atom.jl" is added to precompile now. 
I added other files just for the record.

**Comment by aminya** [comment]
Also, ideally this should run by Travis and the jl files inside precompile folder should be updated. I ran this on the latest registered version.

**Comment by pfitzseb** [comment]
Oh ok, I didn't scroll down all the way :)

So I guess we'd ideally merge this, open PRs against the bigger dependencies (JSON, Tokenize and CSTParser, probably), and get rid of a bunch of random dependencies (Hiccup, Media, CodeTools, Lazy).

I'll play around with this a bit later today or tomorrow, but thanks for taking the initiative on this! :)

**Comment by aviatesk** [comment]
just for info: we should care about this kind of regression: https://github.com/bicycle1885/TableReader.jl/issues/58

**Comment by aminya** [comment]
Can you guys run the benchmark from the file that I added? I have a hard time running the benchmark outside of the Atom. Running it from inside the atom gives the wrong information as it is already loaded.

**Comment by aminya** [comment]
> 
> 
> just for info: we should care about this kind of regression: [bicycle1885/TableReader.jl#58](https://github.com/bicycle1885/TableReader.jl/issues/58)

I added an issue for creating a Github action to automatically update the precompile files
https://github.com/timholy/SnoopCompile.jl/issues/37

**Comment by aviatesk** [comment]
> Yes, only "deps/SnoopCompile/precompile/precompile_Atom.jl" is added to precompile now.
> I added other files just for the record.

could you ignore/rm those files ? They look pretty messy as is.

**Comment by aminya** [comment]
> > Yes, only "deps/SnoopCompile/precompile/precompile_Atom.jl" is added to precompile now.
> > I added other files just for the record.
> 
> could you please ignore/rm those files ? They look pretty messy as is.
Cleaned up ♻️

**Comment by aminya** [comment]
I added Github actions for automatically creating the precompile file. Could you guys test it?

**Comment by aminya** [comment]
The test is passed here:
https://github.com/aminya/Atom.jl/commit/d127e7360362a0485ba598c830b330ab088cecc2/checks?check_suite_id=355123378

I think now you can merge this.

**Comment by aminya** [comment]
For [Atom](https://github.com/JunoLab/Atom.jl/pull/225), runtests.jl uses `@__DIR__` internally for path completion test, which makes the test fail. Because the test runs from our macro,  `@__DIR__`  gives the wrong answer.
https://github.com/aminya/Atom.jl/commit/66cadabcaebe1854795fe1767a797ec5bb248c98/checks?check_suite_id=377070146

Could you change the test to fix this problem?
Maybe using `pwd()` instead of `@__DIR__`

**Comment by aminya** [comment]
I fixed the issue by `test_skip`ing one of the tests.

**Comment by aminya** [comment]
When I add precompilation sentences generated by Atom some of the tests fail (from modules.jl and goto.jl).

https://github.com/aminya/Atom.jl/commit/6aadc52f978fef0ebefa0c115364e8458482ddce/checks?check_suite_id=379165136

**Comment by aviatesk** [comment]
Can you revert 48256f2 and just rebase to our master ? Currently the commit history and diffs are confusing.

**Comment by aviatesk** [comment]
> Could you change the test to fix this problem?
> Maybe using `pwd()` instead of `@__DIR__`

Let's first explain why do we need your fork of SnoopCompile.jl, and what `@snoopBot` is supposed to do.
For this specific issue, I guess you can fix this just by escaping testing expressions in your macro. imho prohibit using macros in future tests are definitely not ideal.

**Comment by aminya** [comment]
Could you wait until I merge my PR into SnoopCompile? There is more documentation and information about the functionality in the PR.

https://github.com/timholy/SnoopCompile.jl/pull/49

**Comment by aviatesk** [comment]
yep, of course. But address https://github.com/JunoLab/Atom.jl/pull/225#issuecomment-570875921 anyway, please 👍

**Comment by aminya** [comment]
So I updated the PR. Now it uses the latest registered SnoopCompile.
To review this PR, just check the end result and don't look at the history, as history includes drastic changes!


For Atom's precompilation, I used `runtests.jl` except `modules.jl` and `goto.jl`. Those were causing errors in loading after precompiling. 

However, even by excluding that after precompilation, Atom's tests result in an error in `modules.jl`:
https://github.com/aminya/Atom.jl/commit/bab8c9801370192d805cfa88394d9b37f45a048c/checks?check_suite_id=400475446#step:8:125

So now I am going to disable the Benchmark step to let the PR get created and see which precompilation signatures cause this error. We can pass them to `Botconfig( "Atom" ;blacklist = ["",...])`

**Comment by aminya** [comment]
I found the problems.

1) we should not precompile `realpath'`
2) `"precompile_Atom.jl"` file is generated by the bot:
https://github.com/aminya/Atom.jl/pull/7
However, `modulefiles` doesn't consider this file as `atommodfiles` not match `includedfiles`
https://github.com/JunoLab/Atom.jl/pull/225/commits/6ed03b5b34e73e7c0953aa5622833019b39be8ee

Could you update these functions to ignore `"precompile_Atom.jl" `

**Comment by aminya** [comment]
@aviatesk @pfitzseb Can you solve this issue? This is ready to get merged. You just need to ignore `"precompile_Atom.jl"` in `modulefiles` test

**Comment by aminya** [comment]
Yay! the problem is fixed. Atom infer time is enhanced by 15.2% :rocket:
The PR can be merged now

https://github.com/aminya/Atom.jl/runs/409909332?check_suite_focus=true

I didn't benchmark the actual timing but infer time is reduced by 2.67s which is 15.2%.

**Pull request merged**
