### PR TITLE
various backtrace-rendering improvements

### PR DESCRIPTION
**Pull request by pfitzseb**
Inspired by #49.

Also shows no expand arrow when there's nothing to expand to, though we could just solve that in `julia-client` and have no arrow when `children` is empty.

cc @KristofferC

### CODE REVIEW

**Comment by MikeInnes** [comment]
Looks good! Thanks to @KristofferC for kicking this off.

**Comment by KristofferC** [comment]
No problem :)

**Comment by MikeInnes** [comment]
@pfitzseb In the console I'm still getting a spurious `include_string`, could you check that out?

**Comment by pfitzseb** [comment]
The backtrace there is 
```
...
 in error(::String) at .\error.jl:21
 in include_string(::String, ::String) at .\loading.jl:380
 in include_string(::String) at .\loading.jl:384
 in eval(::Module, ::Any) at .\boot.jl:234
...
```
so `findlast` doesn't do the right thing then. Not sure if switching back to `findirst` is the right choice though.

**Comment by MikeInnes** [comment]
I'm just going to change console eval to call the (String, String) method directly

**Comment by KristofferC** [comment]
Backtraces so sneaky...

**Comment by KristofferC** [comment]
Something seems to be off

```jl
ERROR (unhandled task failure): TypeError: stacktrace: in typeassert, expected Array{StackFrame,1}, got Array{Any,1}
 in stacktrace(::Array{Ptr{Void},1}, ::Bool) at ./stacktraces.jl:147
 in btlines(::Array{Ptr{Void},1}) at /home/kristoffer/.julia/v0.5/Atom/src/display/errors.jl:19
 in render(::Atom.Editor, ::Atom.EvalError) at /home/kristoffer/.julia/v0.5/Atom/src/display/errors.jl:50
 in macro expansion at /home/kristoffer/.julia/v0.5/Atom/src/comm.jl:24 [inlined]
 in (::Atom.##5#8)() at ./event.jl:46
```

I got this warning at the same time

```jl
WARNING: MethodError(MeshIO.load,(FileIO.File{FileIO.DataFormat{:ABAQUS_INP}}("/home/kristoffer/neper-neutral/build/n10-id1_2D.inp"),))
 in #load#17(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:ABAQUS_INP}}) at /home/kristoffer/.julia/v0.5/FileIO/src/loadsave.jl:82
 in load(::FileIO.File{FileIO.DataFormat{:ABAQUS_INP}}) at /home/kristoffer/.julia/v0.5/FileIO/src/loadsave.jl:73
 in #load#13(::Array{Any,1}, ::Function, ::String) at /home/kristoffer/.julia/v0.5/FileIO/src/loadsave.jl:45
 in load(::String) at /home/kristoffer/.julia/v0.5/FileIO/src/loadsave.jl:45
 in include_string(::String, ::String) at ./loading.jl:380
 in include_string(::String, ::String, ::Int64) at /home/kristoffer/.julia/v0.5/CodeTools/src/eval.jl:28
 in include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N}) at /home/kristoffer/.julia/v0.5/CodeTools/src/eval.jl:32
 in (::Atom.##87#90{String,Int64,String})() at /home/kristoffer/.julia/v0.5/Atom/src/eval.jl:39
 in withpath(::Atom.##87#90{String,Int64,String}, ::String) at /home/kristoffer/.julia/v0.5/Requires/src/require.jl:37
 in withpath(::Function, ::String) at /home/kristoffer/.julia/v0.5/Atom/src/eval.jl:45
 in macro expansion at /home/kristoffer/.julia/v0.5/Atom/src/eval.jl:56 [inlined]
 in (::Atom.##86#89{String,Int64,String})() at ./task.jl:54

```

**Pull request merged**
