### PR TITLE
add 0.6 testing on travis

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by pfitzseb** [comment]
Thanks!

**Comment by tkelman** [comment]
Is it running?

**Comment by pfitzseb** [comment]
[Nope...](https://travis-ci.org/JunoLab/Atom.jl/builds)
Did I merge too soon?

**Comment by tkelman** [comment]
Well, the merge commit would at least run if things were working correctly.

**Comment by pfitzseb** [comment]
So should I push an empty commit to master to retrigger travis or something?

**Comment by tkelman** [comment]
known issue I guess https://www.traviscistatus.com

**Pull request merged**
