### PR TITLE
WIP: Tests

### PR DESCRIPTION
**Pull request by pfitzseb**

### CODE REVIEW

**Comment by pfitzseb** [comment]
@MikeInnes Could you enable travis for Atom? I don't have the necessary admin rights for that ;)

**Comment by MikeInnes** [comment]
I wouldn't say no to this, though as a rule I suspect that the integration tests in julia-client are more worthwhile to spend time on – since they test for correct behaviour independent of implementation. Testing the implementation can amount to specifying it twice, which isn't necessarily bad but (IMO) doesn't carry as much benefit. (I think we might have had this conversation before though.)

Anyway, will go ahead and enable travis!

**Comment by tkelman** [comment]
bump. julia side unit tests are going to be necessary for proper cross version testing.

**Comment by tkelman** [comment]
any recent progress?

**Comment by pfitzseb** [comment]
Superseded by #60.

**Pull request closed without merging**
