### PR TITLE
RFC: First stab at setting module for console eval

### PR DESCRIPTION
**Pull request by spencerlyon2**
This is the Julia-side of having the console evaluate in the module of the last open Julia buffer.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Related to JunoLab/atom-julia-client#34

**Comment by spencerlyon2** [comment]
This appears to work. Here's a screenshot taken by following these steps:

where before the first call to `current_module()` I was in `~/.julia/v0.4/Atom/src/Atom.jl`, then

**Comment by spencerlyon2** [comment]
I think regardless of what we decide over on JunoLab/atom-julia-client#34, this is probably the right approach on the Julia side

**Comment by Varanas** [comment]
This has been implementd, closing.

**Pull request closed without merging**
