### PR TITLE
Add formatter

### PR DESCRIPTION
**Pull request by aviatesk**
## Purpose

Add formatter for Juno using [DocumentFormat.jl](https://github.com/julia-vscode/DocumentFormat.jl)

The corresponding PR on atom-julia-client side is: https://github.com/JunoLab/atom-julia-client/pull/566

## Results

ezgif com-video-to-gif

## Notes

Still this basically works well, there are obvious problems like below:
- DocumentFormat.jl can't handle user-specified indent option right now, thus the format command would force every indent to `Spaces (4)`.
- The first call for this formatting command has to endure the first compilation overhead (like 3 sec on my machine), and there can be an annoying edge case when an user changes the code on formatted while that.

### CODE REVIEW

**Comment by pfitzseb** [comment]
How does the `using DocumentFormat` affect package load time?

**Comment by aviatesk** [comment]
I _feel_ like there is no obvious delay, but could you tell me how I can calculate that accurately ?

**Comment by pfitzseb** [comment]
You can just `@time using Atom` in a non-Juno REPL (and disregard pre-compilation, obviously).

**Comment by aviatesk** [comment]
Ah so there is no utility like `@btime` on the loading package ...
Anyway I'll try it and report back to you soon.

**Comment by pfitzseb** [comment]
Ok, on my machine the overhead is neglibile:
```
julia> @time using DocumentFormat
  0.115280 seconds (65.70 k allocations: 3.646 MiB)
```

**Comment by aviatesk** [comment]
> Before
```
aviat@Alan MINGW64 ~/julia/JunoLab
$ julia
[ Info: Setting up OhMyREPL ...
[ Info: Setting up Revise ...
  1.377875 seconds (980.15 k allocations: 50.989 MiB, 0.57% gc time)
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time using Atom
  5.601269 seconds (3.31 M allocations: 178.025 MiB, 1.42% gc time)
```

> After
```
aviat@Alan MINGW64 ~/julia/JunoLab
$ julia --project=@.
[ Info: Setting up OhMyREPL ...
[ Info: Setting up Revise ...
  1.407860 seconds (1.03 M allocations: 53.334 MiB, 0.50% gc time)
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time using Atom
  5.930550 seconds (3.31 M allocations: 178.170 MiB, 1.42% gc time)
```

**Pull request merged**
