### PR TITLE
latest thing evaled in the console assigned to `ans`

### PR DESCRIPTION
**Pull request by pfitzseb**
not sure if that change to the evaluation logic is correct, but I think it should be; also not sure if this is really desirable...

### CODE REVIEW

**Comment by MikeInnes** [comment]
The change to eval logic looks right, but it might be best to avoid changing the code string itself. i.e. we could have `eval(mod, :(ans = include_string(...`. Not sure if there are any specific problems with `"ans=$..."` but it seems safer.

**Comment by pfitzseb** [comment]
Hm, I think I tried that but the scoping wasn't quite right. Not sure though (it seems like it should work if I think about it now) and I don't really have time to check now (in China at the moment ;)), so feel free to make that change and close this PR.

**Comment by MikeInnes** [comment]
I'll take a look if I get some time. Enjoy China!

**Comment by MikeInnes** [comment]
One small thought about how this: it might be confusing to have different `ans`s in different modules, but we could do something like

```julia
result = ... do the eval ...
isdefined(mod, :ans) && eval(mod, :(import Main.ans))
eval(mod, :(ans = $result))
```

Probably a little fiddlier than that but you get the idea. Not urgent anyway.

**Comment by MikeInnes** [comment]
I was worried about the edge cases but it turns out the repl doesn't handle them either:

```julia
julia> const ans = 1
1

julia> 2
WARNING: redefining constant ans
2

julia> :foo
ERROR: invalid redefinition of constant ans
```

**Pull request merged**
